# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed8c25f58fb0e6448a9472acd4a8cf76aad9880f9716fb69c51006c19699f69e755a6192d48cacc8e07195162fe4ca6c85e375219cce30ee3473a51a9ddb17e1

test:
  secret_key_base: 137f837b70e9d7a2f585e859653f3defc77173d8aaaefe1de41e12c898b893a908384839b90effb0b8d2cebd7eb2680d61662803efccaada4d89ab21a1c759de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
